const batches = [
    {
      idx: "1",
      batchNumber: "1010000",
      fmBatchId: "B21-920-Q0000A",
      thread: "1:PORTGROUP",
      jobName: "1010000",
      xmlImageCount: "2",
      sourceImageCount: "2",
      batchLength: "2",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 11:00:00",
      recQC: "1",
      recQCWho: null,
      recQCTimestamp: null,
      xmlQC: "1",
      xmlQCWho: null,
      xmlQCTimeStamp: null,
      retouch: "1",
      retouchStatus: null,
      retouchTimestamp: null,
      retouchQC: "1",
      retouchQCWho: null,
      retouchQCTimestamp: null,
      stagingTimestamp: null,
      preRipQC: "0",
      preRipQCWho: null,
      preRipQCTimestamp: null,
      ripType: "Underclass",
      ripPC: null,
      ripStatus: null,
      ripTimestamp: null,
      postRipQC: "1",
      qcWho: null,
      qcTimestamp: null,
      batchTimestamp: null,
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "2",
      batchNumber: "1010001",
      fmBatchId: "B21-720-HRS3UY",
      thread: "2:B21-720-HRS3UY",
      jobName: "1010001",
      xmlImageCount: "1",
      sourceImageCount: "1",
      batchLength: "1",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: null,
      transferTimestamp: null,
      recQC: "1",
      recQCWho: null,
      recQCTimestamp: null,
      xmlQC: "1",
      xmlQCWho: null,
      xmlQCTimeStamp: null,
      retouch: "1",
      retouchStatus: null,
      retouchTimestamp: null,
      retouchQC: "1",
      retouchQCWho: null,
      retouchQCTimestamp: null,
      stagingTimestamp: null,
      preRipQC: "0",
      preRipQCWho: null,
      preRipQCTimestamp: null,
      ripType: "Underclass",
      ripPC: null,
      ripStatus: null,
      ripTimestamp: null,
      postRipQC: "1",
      qcWho: null,
      qcTimestamp: null,
      batchTimestamp: null,
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "3",
      batchNumber: "1010002",
      fmBatchId: "B21-813-50DYPC",
      thread: "3:B21-813-50DYPC",
      jobName: "1010002",
      xmlImageCount: "1",
      sourceImageCount: "1",
      batchLength: "1",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:00:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:08:00",
      xmlQC: "1",
      xmlQCWho: null,
      xmlQCTimeStamp: null,
      retouch: "1",
      retouchStatus: null,
      retouchTimestamp: null,
      retouchQC: "1",
      retouchQCWho: null,
      retouchQCTimestamp: null,
      stagingTimestamp: null,
      preRipQC: "0",
      preRipQCWho: null,
      preRipQCTimestamp: null,
      ripType: "Underclass",
      ripPC: null,
      ripStatus: null,
      ripTimestamp: null,
      postRipQC: "1",
      qcWho: null,
      qcTimestamp: null,
      batchTimestamp: null,
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "4",
      batchNumber: "1010003",
      fmBatchId: "B100001",
      thread: "4:B100001",
      jobName: "1010003",
      xmlImageCount: "1",
      sourceImageCount: "1",
      batchLength: "1",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:01:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:02:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:10:00",
      retouch: "1",
      retouchStatus: "retouching",
      retouchTimestamp: null,
      retouchQC: "1",
      retouchQCWho: null,
      retouchQCTimestamp: null,
      stagingTimestamp: null,
      preRipQC: "0",
      preRipQCWho: null,
      preRipQCTimestamp: null,
      ripType: "Underclass",
      ripPC: null,
      ripStatus: null,
      ripTimestamp: null,
      postRipQC: "1",
      qcWho: null,
      qcTimestamp: null,
      batchTimestamp: null,
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "5",
      batchNumber: "1010004",
      fmBatchId: "B21-915-QF0WVU",
      thread: "5:B21-915-QF0WVU",
      jobName: "1010004",
      xmlImageCount: "1",
      sourceImageCount: "1",
      batchLength: "1",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:01:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:07:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:13:00",
      retouch: "1",
      retouchStatus: "retouched",
      retouchTimestamp: "2021-09-20 13:23:00",
      retouchQC: "1",
      retouchQCWho: null,
      retouchQCTimestamp: null,
      stagingTimestamp: null,
      preRipQC: "0",
      preRipQCWho: null,
      preRipQCTimestamp: null,
      ripType: "Underclass",
      ripPC: null,
      ripStatus: null,
      ripTimestamp: null,
      postRipQC: "1",
      qcWho: null,
      qcTimestamp: null,
      batchTimestamp: null,
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "6",
      batchNumber: "1010010",
      fmBatchId: "B21-920-Q0000G",
      thread: null,
      jobName: "1010010",
      xmlImageCount: "2",
      sourceImageCount: "2",
      batchLength: "2",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:01:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:10:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:12:00",
      retouch: "1",
      retouchStatus: "retouched",
      retouchTimestamp: "2021-09-20 13:30:00",
      retouchQC: "1",
      retouchQCWho: "jay.freeman",
      retouchQCTimestamp: "2021-09-20 13:30:00",
      stagingTimestamp: "2021-09-20 13:30:00",
      preRipQC: "0",
      preRipQCWho: null,
      preRipQCTimestamp: null,
      ripType: "Underclass",
      ripPC: null,
      ripStatus: null,
      ripTimestamp: null,
      postRipQC: "1",
      qcWho: null,
      qcTimestamp: null,
      batchTimestamp: null,
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "7",
      batchNumber: "1010011",
      fmBatchId: "B21-920-Q0000H",
      thread: null,
      jobName: "1010011",
      xmlImageCount: "2",
      sourceImageCount: "2",
      batchLength: "2",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:02:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:11:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:13:00",
      retouch: "1",
      retouchStatus: "retouched",
      retouchTimestamp: "2021-09-20 13:31:00",
      retouchQC: "1",
      retouchQCWho: "jay.freeman",
      retouchQCTimestamp: "2021-09-20 13:32:00",
      stagingTimestamp: "2021-09-20 13:32:00",
      preRipQC: "0",
      preRipQCWho: null,
      preRipQCTimestamp: null,
      ripType: "Underclass",
      ripPC: "SSI-1023-IT",
      ripStatus: "ripping",
      ripTimestamp: null,
      postRipQC: "1",
      qcWho: null,
      qcTimestamp: null,
      batchTimestamp: null,
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "8",
      batchNumber: "1010012",
      fmBatchId: "B21-920-Q0000I",
      thread: null,
      jobName: "1010012",
      xmlImageCount: "2",
      sourceImageCount: "2",
      batchLength: "2",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:02:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:11:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:13:00",
      retouch: "1",
      retouchStatus: "retouched",
      retouchTimestamp: "2021-09-20 13:31:00",
      retouchQC: "1",
      retouchQCWho: "jay.freeman",
      retouchQCTimestamp: "2021-09-20 13:32:00",
      stagingTimestamp: "2021-09-20 13:32:00",
      preRipQC: "0",
      preRipQCWho: null,
      preRipQCTimestamp: null,
      ripType: "Underclass",
      ripPC: "SSI-1023-IT",
      ripStatus: "ripped",
      ripTimestamp: "2021-09-20 14:00:00",
      postRipQC: "1",
      qcWho: null,
      qcTimestamp: null,
      batchTimestamp: null,
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "9",
      batchNumber: "1010013",
      fmBatchId: "B21-920-Q0000J",
      thread: null,
      jobName: "1010013",
      xmlImageCount: "2",
      sourceImageCount: "2",
      batchLength: "2",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:02:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:11:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:13:00",
      retouch: "1",
      retouchStatus: "retouched",
      retouchTimestamp: "2021-09-20 13:31:00",
      retouchQC: "1",
      retouchQCWho: "jay.freeman",
      retouchQCTimestamp: "2021-09-20 13:32:00",
      stagingTimestamp: "2021-09-20 13:32:00",
      preRipQC: "0",
      preRipQCWho: null,
      preRipQCTimestamp: null,
      ripType: "Underclass",
      ripPC: "SSI-1023-IT",
      ripStatus: "ripped",
      ripTimestamp: "2021-09-20 14:00:00",
      postRipQC: "1",
      qcWho: "jay.freeman",
      qcTimestamp: "2021-09-20 14:08:00",
      batchTimestamp: "2021-09-20 14:10:00",
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "10",
      batchNumber: "1010014",
      fmBatchId: "B21-920-Q0000K",
      thread: null,
      jobName: "1010014",
      xmlImageCount: "2",
      sourceImageCount: "2",
      batchLength: "2",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:02:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:11:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:13:00",
      retouch: "1",
      retouchStatus: "retouched",
      retouchTimestamp: "2021-09-20 13:31:00",
      retouchQC: "1",
      retouchQCWho: "jay.freeman",
      retouchQCTimestamp: "2021-09-20 13:32:00",
      stagingTimestamp: "2021-09-20 13:32:00",
      preRipQC: "0",
      preRipQCWho: null,
      preRipQCTimestamp: null,
      ripType: "Underclass",
      ripPC: "SSI-1023-IT",
      ripStatus: "ripped",
      ripTimestamp: "2021-09-20 14:00:00",
      postRipQC: "1",
      qcWho: "jay.freeman",
      qcTimestamp: "2021-09-20 14:08:00",
      batchTimestamp: "2021-09-20 14:10:00",
      printingStatus: "printing",
      printingPrinter: "NOR4",
      printingTimeStamp: "2021-09-20 14:12:00"
    },
    {
      idx: "11",
      batchNumber: "1010015",
      fmBatchId: "B21-920-Q0000L",
      thread: "",
      jobName: "1010015",
      xmlImageCount: "1",
      sourceImageCount: "1",
      batchLength: "1",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:01:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:02:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:10:00",
      retouch: "0",
      retouchStatus: null,
      retouchTimestamp: null,
      retouchQC: "0",
      retouchQCWho: null,
      retouchQCTimestamp: null,
      stagingTimestamp: "2021-09-20 13:10:00",
      preRipQC: "1",
      preRipQCWho: null,
      preRipQCTimestamp: null,
      ripType: "Underclass",
      ripPC: null,
      ripStatus: null,
      ripTimestamp: null,
      postRipQC: "1",
      qcWho: null,
      qcTimestamp: null,
      batchTimestamp: null,
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "12",
      batchNumber: "1010016",
      fmBatchId: "B21-920-Q0000M",
      thread: null,
      jobName: "1010016",
      xmlImageCount: "1",
      sourceImageCount: "1",
      batchLength: "1",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:01:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:07:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:13:00",
      retouch: "0",
      retouchStatus: null,
      retouchTimestamp: null,
      retouchQC: "0",
      retouchQCWho: null,
      retouchQCTimestamp: null,
      stagingTimestamp: "2021-09-20 13:13:00",
      preRipQC: "1",
      preRipQCWho: "jay.freeman",
      preRipQCTimestamp: "2021-09-20 13:14:00",
      ripType: "Underclass",
      ripPC: "SSI-1032-IT",
      ripStatus: "ripping",
      ripTimestamp: null,
      postRipQC: "1",
      qcWho: null,
      qcTimestamp: null,
      batchTimestamp: null,
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "13",
      batchNumber: "1010017",
      fmBatchId: "B21-920-Q000AA",
      thread: null,
      jobName: "1010017",
      xmlImageCount: "2",
      sourceImageCount: "2",
      batchLength: "2",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:01:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:10:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:12:00",
      retouch: "1",
      retouchStatus: null,
      retouchTimestamp: null,
      retouchQC: "0",
      retouchQCWho: null,
      retouchQCTimestamp: null,
      stagingTimestamp: "2021-09-20 13:30:00",
      preRipQC: "0",
      preRipQCWho: "jay.freeman",
      preRipQCTimestamp: "2021-09-20 13:31:00",
      ripType: "Underclass",
      ripPC: "SSI-1032-IT",
      ripStatus: "ripped",
      ripTimestamp: "2021-09-20 13:34:00",
      postRipQC: "1",
      qcWho: null,
      qcTimestamp: null,
      batchTimestamp: null,
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "14",
      batchNumber: "1010019",
      fmBatchId: "B21-920-Q000AB",
      thread: null,
      jobName: "1010018",
      xmlImageCount: "2",
      sourceImageCount: "2",
      batchLength: "2",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:02:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:11:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:13:00",
      retouch: "0",
      retouchStatus: null,
      retouchTimestamp: null,
      retouchQC: "0",
      retouchQCWho: null,
      retouchQCTimestamp: null,
      stagingTimestamp: "2021-09-20 13:32:00",
      preRipQC: "0",
      preRipQCWho: "jay.freeman",
      preRipQCTimestamp: "2021-09-20 13:33:00",
      ripType: "Underclass",
      ripPC: "SSI-1023-IT",
      ripStatus: "ripped",
      ripTimestamp: "2021-09-20 13:36:00",
      postRipQC: "1",
      qcWho: "jay.freeman",
      qcTimestamp: "2021-09-20 13:38:00",
      batchTimestamp: "2021-09-20 13:39:00",
      printingStatus: null,
      printingPrinter: null,
      printingTimeStamp: null
    },
    {
      idx: "15",
      batchNumber: "1010019",
      fmBatchId: "B21-920-Q000AC",
      thread: null,
      jobName: "1010019",
      xmlImageCount: "2",
      sourceImageCount: "2",
      batchLength: "2",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:02:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:11:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:13:00",
      retouch: "0",
      retouchStatus: null,
      retouchTimestamp: null,
      retouchQC: "0",
      retouchQCWho: null,
      retouchQCTimestamp: null,
      stagingTimestamp: "2021-09-20 13:32:00",
      preRipQC: "1",
      preRipQCWho: "jay.freeman",
      preRipQCTimestamp: "2021-09-20 13:33:00",
      ripType: "Underclass",
      ripPC: "SSI-1023-IT",
      ripStatus: "ripped",
      ripTimestamp: "2021-09-20 14:35:00",
      postRipQC: "1",
      qcWho: "jay.freeman",
      qcTimestamp: "2021-09-20 13:37:00",
      batchTimestamp: "2021-09-20 13:38:00",
      printingStatus: "printing",
      printingPrinter: "WP1",
      printingTimeStamp: "2021-09-20 13:40:00"
    },
    {
      idx: "16",
      batchNumber: "1010020",
      fmBatchId: "B21-920-Q000AD",
      thread: null,
      jobName: "1010020",
      xmlImageCount: "2",
      sourceImageCount: "2",
      batchLength: "2",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:02:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:11:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:13:00",
      retouch: "0",
      retouchStatus: null,
      retouchTimestamp: null,
      retouchQC: "0",
      retouchQCWho: null,
      retouchQCTimestamp: null,
      stagingTimestamp: "2021-09-20 13:32:00",
      preRipQC: "0",
      preRipQCWho: "jay.freeman",
      preRipQCTimestamp: "2021-09-20 13:32:00",
      ripType: "Underclass",
      ripPC: "SSI-1023-IT",
      ripStatus: "ripped",
      ripTimestamp: "2021-09-20 14:00:00",
      postRipQC: "1",
      qcWho: "jay.freeman",
      qcTimestamp: "2021-09-20 14:08:00",
      batchTimestamp: "2021-09-20 14:10:00",
      printingStatus: "printing",
      printingPrinter: "NOR5",
      printingTimeStamp: "2021-09-20 14:20:00"
    },
    {
      idx: "17",
      batchNumber: "1010021",
      fmBatchId: "B21-920-Q000AE",
      thread: null,
      jobName: "1010021",
      xmlImageCount: "2",
      sourceImageCount: "2",
      batchLength: "2",
      paperWidth: "10",
      paperSurface: "Luster",
      envelopeType: "Underclass",
      shipMethod: "S2H",
      transferStatus: "transferred",
      transferTimestamp: "2021-09-20 13:02:00",
      recQC: "1",
      recQCWho: "jay.freeman",
      recQCTimestamp: "2021-09-20 13:11:00",
      xmlQC: "1",
      xmlQCWho: "jay.freeman",
      xmlQCTimeStamp: "2021-09-20 13:13:00",
      retouch: "0",
      retouchStatus: null,
      retouchTimestamp: null,
      retouchQC: "0",
      retouchQCWho: null,
      retouchQCTimestamp: null,
      stagingTimestamp: "2021-09-20 13:32:00",
      preRipQC: "1",
      preRipQCWho: "jay.freeman",
      preRipQCTimestamp: "2021-09-20 13:32:00",
      ripType: "Underclass",
      ripPC: "SSI-1023-IT",
      ripStatus: "ripped",
      ripTimestamp: "2021-09-20 14:00:00",
      postRipQC: "1",
      qcWho: "jay.freeman",
      qcTimestamp: "2021-09-20 14:08:00",
      batchTimestamp: "2021-09-20 14:10:00",
      printingStatus: "printing",
      printingPrinter: "NOR4",
      printingTimeStamp: "2021-09-20 14:12:00"
    }
  ];
  
  module.exports = batches;
  