const orders = [
    {
      idloroco_test: 32213,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-DA6MT",
      customerName: "Christian Ayon",
      emailAddress: "frida_s2.celina@yahoo.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 20,
      fmhvPackageCost: 20,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Christian",
      parentLastName: "Ayon",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Derby North Middle School",
      _fktCustomerNo: "114770",
      TM: "WMS",
      fmhvSession: "Fall Pictures 9-2-2021",
      _fknShootNumber: "366003",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Christian",
      studentLastName: "Ayon",
      teacher: null,
      grade: "06",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA8WY4QYBKB0MRR0MNYFK6",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32214,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-OY22A",
      customerName: "Tyler Wilcox",
      emailAddress: "dwilcox262003@yahoo.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 18,
      fmhvPackageCost: 18,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Derrick",
      parentLastName: "Wilcox",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Rampello K-8 School",
      _fktCustomerNo: "112009",
      TM: "RC",
      fmhvSession: "Fall Pictures 9-2-2021",
      _fknShootNumber: "368779",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Tyler",
      studentLastName: "Wilcox",
      teacher: null,
      grade: "04",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEF7VRQMREZGJ9NRKQD18S4S",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32215,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-09OL2",
      customerName: "Brittany",
      emailAddress: "kitkat4686@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 45,
      fmhvPackageCost: 45,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Brittany",
      parentLastName: "Scheidel",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Mabel-Canton Public School",
      _fktCustomerNo: "114252",
      TM: "KML",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "352696",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Jaden",
      studentLastName: "Torgerson",
      teacher: null,
      grade: "10",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEF9TCGBE1KVSTJ4P0C62YSB",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32216,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-7GDU9",
      customerName: "Brittany",
      emailAddress: "kitkat4686@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 37,
      fmhvPackageCost: 37,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Brittany",
      parentLastName: "Scheidel",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Mabel-Canton Public School",
      _fktCustomerNo: "114252",
      TM: "KML",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "352696",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Gracelyn",
      studentLastName: "Torgerson",
      teacher: null,
      grade: "05",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEF9VDM9ZAM5D2PQQYYZ7PVF",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32217,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-S924M",
      customerName: "Clare Spear",
      emailAddress: "cbryant77@yahoo.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 21,
      fmhvPackageCost: 21,
      fmhvShipCost: null,
      shippingDiscount: 0,
      shippingMethod: null,
      fmhvShipCode: null,
      parentFirstName: "Clare",
      parentLastName: "Spear",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Commerce Elementary School",
      _fktCustomerNo: "112647",
      TM: "JJR",
      fmhvSession: "Fall Pictures 8-12-2021",
      _fknShootNumber: "357692",
      fmhvStage: "Spec",
      fmhvSeason: "Fall Spec 2021-2022",
      seasonExternalReference: "Fall Spec 2021-2022",
      onlineCode: "FM3576921263",
      studentFirstName: "Bryant",
      studentLastName: "Spear",
      teacher: "Brown",
      grade: "04",
      studentID: "55970",
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAE93AYFEA561QR0Z7Q7XR",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32218,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-UCWTN",
      customerName: "Megan",
      emailAddress: "mtieman@hotmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 13,
      fmhvPackageCost: 13,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Megan",
      parentLastName: "Wegford",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Turkey Foot Middle School",
      _fktCustomerNo: "110694",
      TM: "DRR",
      fmhvSession: "Sports Pictures 8-30-2021",
      _fknShootNumber: "366826",
      fmhvStage: "1. Sports Pre-Pay",
      fmhvSeason: "Sports 2021-2022",
      seasonExternalReference: "Sports 2021-2022",
      onlineCode: null,
      studentFirstName: null,
      studentLastName: null,
      teacher: null,
      grade: "Unknown",
      studentID: null,
      relationshipToStudent: "Unknown",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAA6C2Y2ZGSSSZ64KT7ZP4",
      fmhvCategory: "Sports",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32219,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-Z8PPQ",
      customerName: "Jamari Riley",
      emailAddress: "marshasr78@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 23,
      fmhvPackageCost: 23,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Jamari",
      parentLastName: "Riley",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Hollywood Hills Elementary School",
      _fktCustomerNo: "109663",
      TM: "ROS",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "362403",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Jamari",
      studentLastName: "Riley",
      teacher: "Ms. Kiley",
      grade: "03",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEF9FT5P0GZFEGSK891TDRA1",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32220,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-01VDW",
      customerName: "Apryl Archibald",
      emailAddress: "cjarchibald@sbcglobal.net",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 33,
      fmhvPackageCost: 33,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Sandy",
      parentLastName: "Archibald",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Robinson Middle School",
      _fktCustomerNo: "113375",
      TM: "WMS",
      fmhvSession: "Fall Pictures 9-3-2021",
      _fknShootNumber: "365720",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Apryl",
      studentLastName: "Archibald",
      teacher: null,
      grade: "08",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEF9F2F4AMSYBS6HS06H3WQQ",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32221,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-4VP4C",
      customerName: "Nichole Nellum",
      emailAddress: "merical.nichole@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 33,
      fmhvPackageCost: 33,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Nichole",
      parentLastName: "Nellum",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Longleaf Middle School",
      _fktCustomerNo: "108386",
      TM: "RW",
      fmhvSession: "Fall Pictures 9-2-2021",
      _fknShootNumber: "359007",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Autumn",
      studentLastName: "Nellum",
      teacher: "Leveretter",
      grade: "08",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA7BX41VJNYS4RWKFFF3T6",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32222,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-R96E1",
      customerName: "Beth Anne Dittmer",
      emailAddress: "bethannem40@hotmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 20,
      fmhvPackageCost: 20,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Beth",
      parentLastName: "Anne Dittmer",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Stone Creek Elementary School",
      _fktCustomerNo: "114775",
      TM: "WMS",
      fmhvSession: "Fall Pictures 9-2-2021",
      _fknShootNumber: "365633",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Grant",
      studentLastName: "Dittmer",
      teacher: null,
      grade: "10",
      studentID: null,
      relationshipToStudent: "Other",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAFBKHC00VHHXMKTA05NX5",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32223,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-AB23V",
      customerName: "Nicole cimadamore",
      emailAddress: "Jrzegrl68@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 160.45,
      fmhvPackageCost: 140,
      fmhvShipCost: 9.95,
      shippingDiscount: 0,
      shippingMethod: "Ship to Home",
      fmhvShipCode: "SEN_SHIP_HOME",
      parentFirstName: "Carolyn",
      parentLastName: "B Cimadamore",
      homeAddress: "1400 Eastview Drive",
      homeAddress2: null,
      homeCity: "Aberdeen",
      homeZip: "28315",
      homePhone1: "9109882286",
      homeState: "NC",
      clientName: "Pinecrest High School",
      _fktCustomerNo: "100761",
      TM: "GP",
      fmhvSession: "Senior Portraits 2022",
      _fknShootNumber: "Senior1007612022",
      fmhvStage: "1. Expressions Seniors Standard",
      fmhvSeason: "Seniors2022",
      seasonExternalReference: "Seniors2022",
      onlineCode: "FM1007612080",
      studentFirstName: "Nicole",
      studentLastName: "Cimadamore",
      teacher: null,
      grade: "12",
      studentID: "12057633",
      relationshipToStudent: "Unknown",
      namesOnPrints: "Nicole",
      graduationYear: null,
      orderID: "01FEFABGN14T4RXD3HA1KR5FEZ",
      fmhvCategory: "Senior",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32224,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-BU1J9",
      customerName: "Lisa Larson",
      emailAddress: "lisa.v.Larson@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 18,
      fmhvPackageCost: 18,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Lisa",
      parentLastName: "Larson",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Minnetonka High School",
      _fktCustomerNo: "112988",
      TM: "KML",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "364102",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Joshua",
      studentLastName: "Larson",
      teacher: null,
      grade: "09",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA6AWV5S1G2QS1PQDR1ZXD",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32225,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-44FF0",
      customerName: "Lisa Larson",
      emailAddress: "lisa.v.Larson@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 28,
      fmhvPackageCost: 28,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Lisa",
      parentLastName: "Larson",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Minnetonka High School",
      _fktCustomerNo: "112988",
      TM: "KML",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "364102",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Parker",
      studentLastName: "Larson",
      teacher: null,
      grade: "11",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA7C1T0SXT502W9A2CX38E",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32226,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-GF5RT",
      customerName: "Luke Pulliam",
      emailAddress: "pulliumlt@roxborocommunityschool.org",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 133.58,
      fmhvPackageCost: 115,
      fmhvShipCost: 9.95,
      shippingDiscount: 0,
      shippingMethod: "Ship to Home",
      fmhvShipCode: "SEN_SHIP_HOME",
      parentFirstName: "Holly",
      parentLastName: "R Pulliam",
      homeAddress: "1383 Shiloh Church Road",
      homeAddress2: null,
      homeCity: "Roxboro",
      homeZip: "27574",
      homePhone1: "3363221780",
      homeState: "NC",
      clientName: "Roxboro Community School",
      _fktCustomerNo: "108470",
      TM: "GP",
      fmhvSession: "Senior Portraits 2022",
      _fknShootNumber: "Senior1084702022",
      fmhvStage: "1. Simply Seniors Standard",
      fmhvSeason: "Seniors2022",
      seasonExternalReference: "Seniors2022",
      onlineCode: "FM1084702064",
      studentFirstName: "Luke",
      studentLastName: "Pulliam",
      teacher: null,
      grade: "12",
      studentID: "12090878",
      relationshipToStudent: "Unknown",
      namesOnPrints: "Luke",
      graduationYear: "2022",
      orderID: "01FEF9ADY34B3T7249XZSYMY24",
      fmhvCategory: "Senior",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32227,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-GKQ9B",
      customerName: "Paul Kuhn",
      emailAddress: "paul@kuhnkc.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 10,
      fmhvPackageCost: 10,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Paul",
      parentLastName: "Kuhn",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Walnut Grove Elementary School",
      _fktCustomerNo: "114686",
      TM: "MRA",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "364731",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Finley",
      studentLastName: "Kuhn",
      teacher: null,
      grade: "K",
      studentID: null,
      relationshipToStudent: "Father",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAEEVFDQMPC7NB5F2EXVQF",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32228,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-MOPU8",
      customerName: "Sonnet Moore",
      emailAddress: "sonnetdm16@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 34,
      fmhvPackageCost: 27,
      fmhvShipCost: 7,
      shippingDiscount: 0,
      shippingMethod: "Post Picture Day Order Fee",
      fmhvShipCode: "ORDER_FEE",
      parentFirstName: "Sonnet",
      parentLastName: "Moore",
      homeAddress: "6448 S Barouche",
      homeAddress2: null,
      homeCity: "Pendleton",
      homeZip: "46064",
      homePhone1: "7656025785",
      homeState: "IN",
      clientName: "Pendleton Elementary School",
      _fktCustomerNo: "114787",
      TM: "JGR",
      fmhvSession: "Fall Pictures 8-11-2021",
      _fknShootNumber: "365568",
      fmhvStage: "3. Late Order: Images Posted",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: "FM3655681190",
      studentFirstName: "Avery",
      studentLastName: "Moore",
      teacher: "Miller",
      grade: "06",
      studentID: "506116101",
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEF1AG54VDHAZHWCEW4QDAKA",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32229,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-E2VKB",
      customerName: "Riley Krusmark",
      emailAddress: "rileypierson2@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 28,
      fmhvPackageCost: 28,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Riley",
      parentLastName: "Krusmark",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Goodhue Public School",
      _fktCustomerNo: "113224",
      TM: "KML",
      fmhvSession: "Fall Pictures 8-31-2021",
      _fknShootNumber: "362993",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Maggie",
      studentLastName: "Krusmark",
      teacher: "Pasch",
      grade: "K",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA3D31CBHWRRZGAWDCXBWT",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32230,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-8H0WE",
      customerName: "April Canida",
      emailAddress: "aprilrcanida@yahoo.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 28,
      fmhvPackageCost: 28,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "April",
      parentLastName: "Canida",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Trail Ridge Middle School",
      _fktCustomerNo: "111965",
      TM: "MRA",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "364732",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Layla",
      studentLastName: "Canida",
      teacher: null,
      grade: "06",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA7PJ5PWB305300T0MVKA3",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32231,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-JRFU1",
      customerName: "Leslie Stopyra",
      emailAddress: "lastopyra@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 15,
      fmhvPackageCost: 15,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Leslie",
      parentLastName: "Stopyra",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Calvary Day School",
      _fktCustomerNo: "114966",
      TM: "GF",
      fmhvSession: "Sports Pictures 9-1-2021",
      _fknShootNumber: "370261",
      fmhvStage: "1. Sports Pre-Pay",
      fmhvSeason: "Sports 2021-2022",
      seasonExternalReference: "Sports 2021-2022",
      onlineCode: null,
      studentFirstName: null,
      studentLastName: null,
      teacher: null,
      grade: "Unknown",
      studentID: null,
      relationshipToStudent: "Unknown",
      namesOnPrints: "Mason",
      graduationYear: null,
      orderID: "01FEFAEMDMJC1Q1PXRX9ZEMV35",
      fmhvCategory: "Sports",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32232,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-2H6QX",
      customerName: "Kristin Flowers",
      emailAddress: "KLErhard88@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 50,
      fmhvPackageCost: 50,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "KRISTIN",
      parentLastName: "L FLOWERS",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "H. S. Moody Elementary School",
      _fktCustomerNo: "112049",
      TM: "MJM",
      fmhvSession: "Fall Pictures 9-8-2021",
      _fknShootNumber: "361398",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Nathaniel",
      studentLastName: "Erhard Flowers",
      teacher: "Marines",
      grade: "01",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: "Nathaniel",
      graduationYear: null,
      orderID: "01FEFAA9W4CSMA5BWJFARN5YDW",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32233,
      dateIn: "2021-08-24",
      referenceNumber: "021-824-D14LL",
      customerName: "Michelle Parker",
      emailAddress: "michelleparker1288@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 32,
      fmhvPackageCost: 32,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Michelle",
      parentLastName: "Parker",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "San Jose Elementary School",
      _fktCustomerNo: "113517",
      TM: "AS",
      fmhvSession: "Fall Pictures 9-3-2021",
      _fknShootNumber: "365140",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: 'Larry "Dj"',
      studentLastName: "Griffin",
      teacher: "Dughi",
      grade: "K",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FDX7NXCC1CK0SSSRDXXZG2C3",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-24",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32234,
      dateIn: "2021-08-31",
      referenceNumber: "021-91-JNQFB",
      customerName: "Alexis Klema",
      emailAddress: "christine.klema@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 8,
      fmhvPackageCost: 8,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Alexis",
      parentLastName: "Klema",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Prior Lake High School",
      _fktCustomerNo: "114930",
      TM: "KML",
      fmhvSession: "Fall Pictures 8-31-2021",
      _fknShootNumber: "370153",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Alexis",
      studentLastName: "Klema",
      teacher: null,
      grade: "09",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAM9X812KJ5B2R9DMQHW5J",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32235,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-92UV6",
      customerName: "Tasha Sullivan",
      emailAddress: "ancraft@yahoo.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 23,
      fmhvPackageCost: 23,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Tasha",
      parentLastName: "Sullivan",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Vance Elementary School",
      _fktCustomerNo: "107062",
      TM: "SW",
      fmhvSession: "Fall Pictures 9-9-2021",
      _fknShootNumber: "370289",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Savanna",
      studentLastName: "Sullivan",
      teacher: "Mclaney",
      grade: "K",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAFF0Y1645F5E3VGP9DSS3",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32236,
      dateIn: "2021-08-31",
      referenceNumber: "021-91-IXIED",
      customerName: "Tasha Sullivan",
      emailAddress: "ancraft@yahoo.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 23,
      fmhvPackageCost: 23,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Tasha",
      parentLastName: "Sullivan",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Vance Elementary School",
      _fktCustomerNo: "107062",
      TM: "SW",
      fmhvSession: "Fall Pictures 9-9-2021",
      _fknShootNumber: "370289",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Tobren",
      studentLastName: "Sullivan",
      teacher: "Cherrie",
      grade: "02",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAH336753W76BYFEHPMCHB",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32237,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-LMBXW",
      customerName: "Vanessa Torres",
      emailAddress: "vjtorres94@icloud.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 45,
      fmhvPackageCost: 45,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Vanessa",
      parentLastName: "Torres",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "East Naples Middle School",
      _fktCustomerNo: "109934",
      TM: "SAO",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "362371",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Giovanni",
      studentLastName: "Torres",
      teacher: null,
      grade: "08",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA4NGTF52ZD0TW7H2ZE569",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32238,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-Q2S4T",
      customerName: "Susan Koller",
      emailAddress: "susankoller@hotmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 15,
      fmhvPackageCost: 15,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Susan",
      parentLastName: "Koller",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Minnetonka High School",
      _fktCustomerNo: "112988",
      TM: "KML",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "364102",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Claire",
      studentLastName: "Koller",
      teacher: null,
      grade: "09",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFACA08R6YX370ANMWJS48P",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32239,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-NLF3P",
      customerName: "Susan Koller",
      emailAddress: "susankoller@hotmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 15,
      fmhvPackageCost: 15,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Susan",
      parentLastName: "Koller",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Minnetonka High School",
      _fktCustomerNo: "112988",
      TM: "KML",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "364102",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Bridget",
      studentLastName: "Koller",
      teacher: null,
      grade: "09",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFACT351B3732KTA015M8TP",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32240,
      dateIn: "2021-08-31",
      referenceNumber: "021-91-UN3TR",
      customerName: "Heather Haney",
      emailAddress: "hmhaney@hotmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 8,
      fmhvPackageCost: 8,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Heather",
      parentLastName: "Haney",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Lake Mills High School",
      _fktCustomerNo: "113500",
      TM: "TAG",
      fmhvSession: "Fall Pictures 9-2-2021",
      _fknShootNumber: "368026",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Maya",
      studentLastName: "Loverink",
      teacher: null,
      grade: "06",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAFTRA4S4A7KNDHVPSP6VT",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32241,
      dateIn: "2021-08-31",
      referenceNumber: "021-91-PTH49",
      customerName: "Eli Zachary",
      emailAddress: "kristina.zachary@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 18,
      fmhvPackageCost: 18,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Eli",
      parentLastName: "Zachary",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Southern Alamance High School",
      _fktCustomerNo: "110967",
      TM: "GF",
      fmhvSession: "Fall Pictures 9-2-2021",
      _fknShootNumber: "359941",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Eli",
      studentLastName: "Zachary",
      teacher: "Pritchard",
      grade: "10",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAKFT1SBHF70VPMFN9H6D9",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32242,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-C0IZV",
      customerName: "Michelle Matters",
      emailAddress: "mlm622@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 38,
      fmhvPackageCost: 38,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Michelle",
      parentLastName: "Matters",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "New Prague High School",
      _fktCustomerNo: "114537",
      TM: "KML",
      fmhvSession: "Fall Pictures 9-2-2021",
      _fknShootNumber: "363991",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Logan",
      studentLastName: "Matters",
      teacher: null,
      grade: "09",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEF9Z0XRZ7GF7EXCQFEVV21Y",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32243,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-FSFLX",
      customerName: "Logan Robinson",
      emailAddress: "jessica.b.humphries@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 15,
      fmhvPackageCost: 15,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Jessica",
      parentLastName: "Humphries",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Lumpkin County Middle School",
      _fktCustomerNo: "101286",
      TM: "JJR",
      fmhvSession: "Sports Pictures 8-31-2021",
      _fknShootNumber: "370154",
      fmhvStage: "1. Sports Pre-Pay",
      fmhvSeason: "Sports 2021-2022",
      seasonExternalReference: "Sports 2021-2022",
      onlineCode: null,
      studentFirstName: null,
      studentLastName: null,
      teacher: null,
      grade: "Unknown",
      studentID: null,
      relationshipToStudent: "Unknown",
      namesOnPrints: "Robinson",
      graduationYear: null,
      orderID: "01FEFAEFR5N0J7W9JAZHTHYEN6",
      fmhvCategory: "Sports",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32244,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-DM85L",
      customerName: "WENDY CLARK",
      emailAddress: "WLN0214@YAHOO.COM",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 30,
      fmhvPackageCost: 30,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "WENDY",
      parentLastName: "CLARK",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Morton Ranch Junior High",
      _fktCustomerNo: "112482",
      TM: "WL",
      fmhvSession: "Fall Pictures 9-3-2021",
      _fknShootNumber: "358327",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "JAKOB",
      studentLastName: "CLARK",
      teacher: "MR. CLARK - ADVISORY",
      grade: "06",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAF2SRN64023F2184K5G4A",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32245,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-24G8A",
      customerName: "Daymon Medina Garcia",
      emailAddress: "dmedina2552@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 38,
      fmhvPackageCost: 38,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Daymon",
      parentLastName: "Medina Garcia",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Seven Oaks Elementary School",
      _fktCustomerNo: "114484",
      TM: "MJM",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "359499",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Paola",
      studentLastName: "Medina",
      teacher: "Mary Calcagni",
      grade: "05",
      studentID: null,
      relationshipToStudent: "Father",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA1M42YVJC4Z6AEHWC1X82",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32246,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-YZQN2",
      customerName: "Reanna Wonders",
      emailAddress: "rmwonders@hotmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 37,
      fmhvPackageCost: 37,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Reanna",
      parentLastName: "Wonders",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Wineteer Elementary School",
      _fktCustomerNo: "114778",
      TM: "WMS",
      fmhvSession: "Fall Pictures 9-2-2021",
      _fknShootNumber: "365442",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Noah",
      studentLastName: "Wonders",
      teacher: "A shifflett",
      grade: "K",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEF1PPKQ0S4BB6317ZZFMZHA",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32247,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-9CBIC",
      customerName: "Kimberly Nash",
      emailAddress: "kimb3rly1985@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 24,
      fmhvPackageCost: 24,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Justin",
      parentLastName: "A Nash",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Riverheads Elementary School",
      _fktCustomerNo: "109467",
      TM: "AES",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "371885",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Cameilla",
      studentLastName: "Nash",
      teacher: "MRS. Leonard",
      grade: "05",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEF9REW428HXEWM74616KRXC",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32248,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-XWRJQ",
      customerName: "Karri Larson",
      emailAddress: "klarson@altoona.k12.wi.us",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 20,
      fmhvPackageCost: 20,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Karri",
      parentLastName: "Larson",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Altoona Elementary School",
      _fktCustomerNo: "114699",
      TM: "EJS",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "363623",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Lilliana",
      studentLastName: "Larson",
      teacher: "Mrs. Fleming",
      grade: "03",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA7MTZ7MBWJ0R6RK5Y4Z3C",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32249,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-08S0U",
      customerName: "Karri Larson",
      emailAddress: "klarson@altoona.k12.wi.us",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 20,
      fmhvPackageCost: 20,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Karri",
      parentLastName: "Larson",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Altoona Elementary School",
      _fktCustomerNo: "114699",
      TM: "EJS",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "363623",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Jamison",
      studentLastName: "Larson",
      teacher: "Mrs. Sather",
      grade: "02",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA88ZAAH2177QZ08J9KDBZ",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32250,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-F2O1L",
      customerName: "Jessica Gallagher",
      emailAddress: "jessica.e.gallagher1978@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 34,
      fmhvPackageCost: 34,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Post Picture Day Order Fee",
      fmhvShipCode: "ORDER_FEE",
      parentFirstName: "Jessica",
      parentLastName: "Gallagher",
      homeAddress: "1415 12th St SE",
      homeAddress2: null,
      homeCity: "New Prague",
      homeZip: "56071",
      homePhone1: "9527588837",
      homeState: "MN",
      clientName: "Falcon Ridge Elementary School",
      _fktCustomerNo: "114536",
      TM: "KML",
      fmhvSession: "Fall Pictures 8-24-2021",
      _fknShootNumber: "362980",
      fmhvStage: "2. Late Order: Post Production",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Samuel",
      studentLastName: "Gallagher",
      teacher: "Conway",
      grade: "05",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEF9YN3S9F13KQ52CQ1PYH8E",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32251,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-54CH2",
      customerName: "Jessica Gallagher",
      emailAddress: "jessica.e.gallagher1978@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 34,
      fmhvPackageCost: 34,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Post Picture Day Order Fee",
      fmhvShipCode: "ORDER_FEE",
      parentFirstName: "Jessica",
      parentLastName: "Gallagher",
      homeAddress: "1415 12th St SE",
      homeAddress2: null,
      homeCity: "New Prague",
      homeZip: "56071",
      homePhone1: "9527588837",
      homeState: "MN",
      clientName: "Falcon Ridge Elementary School",
      _fktCustomerNo: "114536",
      TM: "KML",
      fmhvSession: "Fall Pictures 8-24-2021",
      _fknShootNumber: "362980",
      fmhvStage: "2. Late Order: Post Production",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Finnegan",
      studentLastName: "Gallagher",
      teacher: "Prchal",
      grade: "04",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEF9ZB20RJWGN3XFHTMPX4PM",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32252,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-4ZMZ4",
      customerName: "Jessica Gallagher",
      emailAddress: "jessica.e.gallagher1978@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 41,
      fmhvPackageCost: 34,
      fmhvShipCost: 7,
      shippingDiscount: 0,
      shippingMethod: "Post Picture Day Order Fee",
      fmhvShipCode: "ORDER_FEE",
      parentFirstName: "Jessica",
      parentLastName: "Gallagher",
      homeAddress: "1415 12th St SE",
      homeAddress2: null,
      homeCity: "New Prague",
      homeZip: "56071",
      homePhone1: "9527588837",
      homeState: "MN",
      clientName: "Falcon Ridge Elementary School",
      _fktCustomerNo: "114536",
      TM: "KML",
      fmhvSession: "Fall Pictures 8-24-2021",
      _fknShootNumber: "362980",
      fmhvStage: "2. Late Order: Post Production",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Joseph",
      studentLastName: "Gallagher",
      teacher: "Clark",
      grade: "02",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA0HT2B37CZB59X8F6TC8Q",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32253,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-EDGFB",
      customerName: "Barbara Vance",
      emailAddress: "bvance25506@yahoo.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 15,
      fmhvPackageCost: 15,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Barbara",
      parentLastName: "Vance",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Guyan Valley Middle School",
      _fktCustomerNo: "114969",
      TM: "AEZ",
      fmhvSession: "Fall Pictures 9-9-99",
      _fknShootNumber: "370567",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Tila",
      studentLastName: "Cook",
      teacher: "Saunders",
      grade: "06",
      studentID: null,
      relationshipToStudent: "Other",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA1P3YSF1AQ51EF8N57CEA",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32254,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-6V8WW",
      customerName: "Barbara Vance",
      emailAddress: "bvance25506@yahoo.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 15,
      fmhvPackageCost: 15,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Barbara",
      parentLastName: "Vance",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Guyan Valley Middle School",
      _fktCustomerNo: "114969",
      TM: "AEZ",
      fmhvSession: "Fall Pictures 9-9-99",
      _fknShootNumber: "370567",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Hope",
      studentLastName: "Stephens",
      teacher: "Wilson",
      grade: "06",
      studentID: null,
      relationshipToStudent: "Other",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA2K6SBYKRMJ8JAYYZVSBE",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32255,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-KT4PH",
      customerName: "Barbara Vance",
      emailAddress: "bvance25506@yahoo.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 15,
      fmhvPackageCost: 15,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Barbara",
      parentLastName: "Vance",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Guyan Valley Middle School",
      _fktCustomerNo: "114969",
      TM: "AEZ",
      fmhvSession: "Fall Pictures 9-9-99",
      _fknShootNumber: "370567",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "David",
      studentLastName: "Stephens",
      teacher: "Bragg",
      grade: "08",
      studentID: null,
      relationshipToStudent: "Other",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA4VSYG135MY4X4HMHRY41",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32256,
      dateIn: "2021-08-31",
      referenceNumber: "021-91-4EJJS",
      customerName: "Jessica McCaskill",
      emailAddress: "jmccaskill@wcpss.net",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 26,
      fmhvPackageCost: 26,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Jessica",
      parentLastName: "D McCaskill",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Heritage Elementary School",
      _fktCustomerNo: "101396",
      TM: "SW",
      fmhvSession: "Pictures 9-2-2021",
      _fknShootNumber: "367699",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Audrey",
      studentLastName: "McCaskill",
      teacher: "John",
      grade: "01",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAFY190YKMMPC0VSH7N0SA",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32257,
      dateIn: "2021-08-31",
      referenceNumber: "021-91-Q337T",
      customerName: "Jessica McCaskill",
      emailAddress: "jmccaskill@wcpss.net",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 26,
      fmhvPackageCost: 26,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Jessica",
      parentLastName: "D McCaskill",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Heritage Elementary School",
      _fktCustomerNo: "101396",
      TM: "SW",
      fmhvSession: "Pictures 9-2-2021",
      _fknShootNumber: "367699",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "James",
      studentLastName: "McCaskill",
      teacher: "Bunn",
      grade: "05",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAG9VBPFDJT6S3FM4RCR0Y",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32258,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-S6L0J",
      customerName: "Megan Chambers",
      emailAddress: "mbcmegs@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 18,
      fmhvPackageCost: 18,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Megan",
      parentLastName: "Chambers",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Kerr-Vance Academy",
      _fktCustomerNo: "100952",
      TM: "AH",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "372094",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Emma",
      studentLastName: "Chambers",
      teacher: "Munn",
      grade: "09",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFAAKD5D5HPW5CV9E0PPNVS",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32259,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-3UE9G",
      customerName: "Megan Chambers",
      emailAddress: "mbcmegs@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 18,
      fmhvPackageCost: 18,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Megan",
      parentLastName: "Chambers",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Kerr-Vance Academy",
      _fktCustomerNo: "100952",
      TM: "AH",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "372094",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "James",
      studentLastName: "Chambers",
      teacher: "Moseley",
      grade: "04",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA6YG6GHQFYZKYR2WPS85C",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32260,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-B1150",
      customerName: "Megan Chambers",
      emailAddress: "mbcmegs@gmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 18,
      fmhvPackageCost: 18,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Megan",
      parentLastName: "Chambers",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Kerr-Vance Academy",
      _fktCustomerNo: "100952",
      TM: "AH",
      fmhvSession: "Fall Pictures 9-1-2021",
      _fknShootNumber: "372094",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Alexandra",
      studentLastName: "Chambers",
      teacher: "Shaw",
      grade: "09",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA8ZJT8NF97XQQA5GYT6Y6",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32261,
      dateIn: "2021-08-31",
      referenceNumber: "021-91-SMIPM",
      customerName: "Harmony Beckman",
      emailAddress: "harmonybeckman@hotmail.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 22,
      fmhvPackageCost: 22,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Harmony",
      parentLastName: "Beckman",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Prior Lake High School",
      _fktCustomerNo: "114930",
      TM: "KML",
      fmhvSession: "Fall Pictures 8-31-2021",
      _fknShootNumber: "370153",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Drew",
      studentLastName: "Beckman",
      teacher: null,
      grade: "10",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: "Drew",
      graduationYear: null,
      orderID: "01FEFAMVK3Y7AB4715VSMH5XQM",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    },
    {
      idloroco_test: 32262,
      dateIn: "2021-08-31",
      referenceNumber: "021-831-SK93L",
      customerName: "Desirae Trevino",
      emailAddress: "trevino_desirae@yahoo.com",
      _fktPackage: null,
      fmhvPaymentMethod: "stripe",
      fmhvTotal: 20,
      fmhvPackageCost: 20,
      fmhvShipCost: 0,
      shippingDiscount: 0,
      shippingMethod: "Ship to School",
      fmhvShipCode: "SHIP_SCHOOL",
      parentFirstName: "Monica",
      parentLastName: "Silguero",
      homeAddress: null,
      homeAddress2: null,
      homeCity: null,
      homeZip: null,
      homePhone1: null,
      homeState: null,
      clientName: "Faye Webb Elementary School",
      _fktCustomerNo: "108051",
      TM: "JR",
      fmhvSession: "Fall Pictures 8-31-2021",
      _fknShootNumber: "368915",
      fmhvStage: "1. Pre-Pay",
      fmhvSeason: "Fall Prepay 2021-2022",
      seasonExternalReference: "Fall Prepay 2021-2022",
      onlineCode: null,
      studentFirstName: "Mila",
      studentLastName: "Silvas",
      teacher: "Buchanan",
      grade: "K",
      studentID: null,
      relationshipToStudent: "Mother",
      namesOnPrints: null,
      graduationYear: null,
      orderID: "01FEFA92W9AXPPS9YXA282SWM7",
      fmhvCategory: "Fall",
      dateCreated: "2021-08-31",
      dateModified: "2021-08-31",
      datePulled: "2021-09-03",
      batchID: null,
      automation: null,
      lorocoNumber: null,
      batchSequence: null
    }
  ];
  
  module.exports = orders;
  