const fmBatchInfo = [
  {
    batchJobs: [
      {
        type: 'order_distribution_df',
        batchReference: 'B21-106-8LSIP1',
        state: 'STATE_QUEUED_FOR_PROCESSING',
        shippingAddress: {
          name: 'Strawbridge Studios',
          firstName: 'Strawbridge',
          lastName: 'Studios',
          phone: '18003269080',
          address1: '13616 Hillsborough Rd',
          city: 'Durham',
          zipCode: '27705',
          state: 'US-NC',
          stateLabel: 'NC',
          country: 'US',
          countryLabel: 'United States',
          id: 14338,
        },
        sortOrder: [{ property: 'orders.id', direction: 'desc' }],
        shippingMethod: {
          id: '01FCYX3QCC4WNY6727PWTSCGCS',
          type: 'bulk_special',
          supplierCode: 'ORDER_FEE',
          label: 'Post Picture Day Order Fee',
        },
        totalOrders: 2,
        id: '01FHBH14M9BNMQF8963C3YM219',
      },
    ],
  },
  {
    batchJobs: [
      {
        type: 'order_distribution_df',
        batchReference: 'B21-106-I8559V',
        state: 'STATE_QUEUED_FOR_PROCESSING',
        shippingAddress: {
          name: 'Strawbridge Studios',
          firstName: 'Strawbridge',
          lastName: 'Studios',
          phone: '18003269080',
          address1: '13616 Hillsborough Rd',
          city: 'Durham',
          zipCode: '27705',
          state: 'US-NC',
          stateLabel: 'NC',
          country: 'US',
          countryLabel: 'United States',
          id: 14339,
        },
        sortOrder: [{ property: 'orders.id', direction: 'desc' }],
        shippingMethod: {
          id: '01FCYX3QCC4WNY6727PWTSCGCS',
          type: 'bulk_special',
          supplierCode: 'ORDER_FEE',
          label: 'Post Picture Day Order Fee',
        },
        totalOrders: 2,
        id: '01FHBH15E0FKYZ35GWR0HHDHSD',
      },
    ],
  },
  {
    batchJobs: [
      {
        type: 'order_distribution_df',
        batchReference: 'B21-106-19T1DI',
        state: 'STATE_QUEUED_FOR_PROCESSING',
        shippingAddress: {
          name: 'Strawbridge Studios',
          firstName: 'Strawbridge',
          lastName: 'Studios',
          phone: '18003269080',
          address1: '13616 Hillsborough Rd',
          city: 'Durham',
          zipCode: '27705',
          state: 'US-NC',
          stateLabel: 'NC',
          country: 'US',
          countryLabel: 'United States',
          id: 14340,
        },
        sortOrder: [{ property: 'orders.id', direction: 'desc' }],
        shippingMethod: {
          id: '01FCYX3QCC4WNY6727PWTSCGCS',
          type: 'bulk_special',
          supplierCode: 'ORDER_FEE',
          label: 'Post Picture Day Order Fee',
        },
        totalOrders: 3,
        id: '01FHBH165RTZDPGK9RYSZ48MQY',
      },
    ],
  },
];
